version: "3.8"
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=${NGROK_STATIC_DOMAIN}"
      - "5678"
    stdin_open: true
    tty: true
    depends_on:
      - n8n
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${NGROK_STATIC_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${NGROK_STATIC_DOMAIN}
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  flowise:
    image: flowiseai/flowise:latest
    restart: always
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"

volumes:
  n8n_data:
  flowise_data:
