version: "3.8"
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${NGROK_STATIC_DOMAIN}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=${NGROK_STATIC_DOMAIN}"
      - "5678"
    stdin_open: true
    tty: true

volumes:
  n8n_data:
